### PR TITLE
DEX - estimated to receive and total to be swapped - add USD value #2594

### LINKED ISSUE #2594: `DEX` - estimated to receive and total to be swapped - add USD value
#### What would you like to be added:
On the pool swap page, when doing swaps. There is a row called "Estimated to receive" and "Total to be swapped". Add a USD value on it.

image

Layout should look similar to other prices
image

### PR DESCRIPTION
**Pull request by rox1338**
#### What kind of PR is this?:
/kind feature

#### What this PR does / why we need it:
see #2594

#### Which issue(s) does this PR fixes?:
Fixes #2594

### CODE REVIEW

**Comment by rox1338** [comment]
@thedoublejay

**Comment by thedoublejay** [comment]
> @thedoublejay

Hi @rox1338, will review this today. I was out last week, didn't have time to review.

**Comment by pierregee** [comment]
DEX -> Swap (Composite) -> Correct values
DEX -> Swap (any card) -> No values displayed
image

**Review by pierregee — CHANGES_REQUESTED** [review]
DEX -> Swap (Composite) -> Correct values
DEX -> Swap (any card) -> No values displayed
image

**Comment by pierregee** [comment]
@rox1338 could you check if you could add e2e tests in `compositeswap.spec.ts` to make sure that there's a USD value when coming from composite swap and direct swap? 🙏

**Comment by rox1338** [comment]
Sry, but what is the difference between composite and direct swap? @pierregee

**Comment by pierregee** [comment]
> Sry, but what is the difference between composite and direct swap? @pierregee



Composite Swap is the swap button on the upper right
image

Direct Swap is the swap button on each card
image

**Comment by rox1338** [comment]
For me the feature works very well for direct swap too.
I added a check to one of the e2e tests.
Is there an existing e2e test for direct swap? I couldn't find one.

**Comment by pierregee** [comment]
> For me the feature works very well for direct swap too. I added a check to one of the e2e tests. Is there an existing e2e test for direct swap? I couldn't find one.

Yea works my bad! Looks like there isn't any e2e tests for it yet , at least for this specific test, we can just add here - `dex_poolpairs.spec.ts` and just build on top of it

**Comment by rox1338** [comment]
added a test in dex_poolpairs.spec.ts

**Comment by rox1338** [comment]
@thedoublejay

**Pull request merged**
