### PR TITLE
fixed wrong `whale-api-client` imports due to `whale:0.7.0` upgrade

### PR DESCRIPTION
**Pull request by fuxingloh**
#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

~~Updated typescript to `>=4.2.0` to use latest features causing compile IntelliSense errors.~~

Fixed wrong `whale-api-client` imports due to `0.7.0` changes.

```diff
- import { PoolPairData } from '@defichain/whale-api-client/dist/api/poolpair'
+ import { PoolPairData } from '@defichain/whale-api-client/dist/api/poolpairs'
```

### CODE REVIEW

**Comment by thedoublejay** [comment]
I think it's not yet supported yet by Expo.

**Review by thedoublejay — CHANGES_REQUESTED** [review]
I think it's not yet supported yet by Expo. Let's check if the expo upgrade will work

**Comment by fuxingloh** [comment]
> I think it's not yet supported yet by Expo. Let's check if the expo upgrade will work

It's mainly due to this new typescript template feature, I will revert the change in https://github.com/DeFiCh/whale/pull/285

**Comment by fuxingloh** [comment]
> I think it's not yet supported yet by Expo. Let's check if the expo upgrade will work

To keep it on the safe side I will just revert typescript and fix import errors.

**Review by thedoublejay — APPROVED** [review]

**Pull request merged**
