### PR TITLE
fix(ui-ux): translate date formatting and fix various other translati…

### PR DESCRIPTION
**Pull request by thedoublejay**
…ons (#2332)

* fix(ui-ux): translate date formatting and fix various other translations

* fix(ui-ux): translate date formatting and fix various other translations
Switch to another wallet

* fix(ui-ux): translate date formatting and fix various other translations
use import instead of require

* fix(ui-ux): translate date formatting and fix various other translations
import reordering and semicolon fixes

Co-authored-by: JJ Adonis <josejaimecareers@gmail.com>

#### What kind of PR is this?:

/kind feature

#### Which issue(s) does this PR fixes?:

Fixes #

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

**Review by pierregee — APPROVED** [review]
Letting you decide if it should be merged with missing translations in non-DE languages

**Comment by thedoublejay** [comment]
@rox1338 Hi, I will be merging this once translations for other languages are ready

**Comment by thedoublejay** [comment]
Also @rox1338, I will revert the change for `"Switch to another wallet": "Wechsel zu einer anderen Wallet"`. We cannot just change the label for now. Will need to check with design team first

**Comment by rox1338** [comment]
> Also @rox1338, I will revert the change for `"Switch to another wallet": "Wechsel zu einer anderen Wallet"`. We cannot just change the label for now. Will need to check with design team first

I think there is a misunderstanding.
I did not change the label "Switch to another address" to "Switch to another wallet". It was already that way and I think your change to "address" is a mistake as I believe it breaks the translations. Please double-check my commit. @thedoublejay

**Pull request merged**
