### PR TITLE
refactor & fixes for `Network` & `Wallet` issues, `DEX` - APR, `Header` - Network

### LINKED ISSUE #423: `DEX` - show APR on pool pairs
#### What would you like to be added:
Show APR for DEX pool pairs
#### Why is this needed:
/area ui-ux wallet
/priority important-soon
/triage accepted

### LINKED ISSUE #470: `network` not persisted on app re-open
#### What happened:
The current active network is not persisted when you re-open the app. Example, switch to Mainnet and re open the app. It reverts to Playground.
#### Anything else we need to know?:
/triage accepted

### LINKED ISSUE #471: `address` - on change network, remains the same
#### What happened:
On change of network, address remains the same.

### LINKED ISSUE #472: `wallet` - created wallet for mainnet doesn't load
#### What happened:
When you have a mainnet and playground wallet loaded, and you exit playground wallet. It will go to onboarding page, which is expected. When you re-open the app, it should load mainnet wallet since it's existing.

### LINKED ISSUE #473: `onboarding` - restoring a wallet using mainnet mnemonic
#### What happened:
Restoring a wallet using mainnet mnemonic, loads playground network

### LINKED ISSUE #480: `network` - switching networks only update state once
#### What happened:
On initial network change, state updates. However on reverting back to original network. State doesn't change anymore.
#### What you expected to happen:
Playground -> mainnet (state updates)
Mainnet -> playground (state doesn't change anymore)

### PR DESCRIPTION
**Pull request by fuxingloh**
#### What kind of PR is this?:
/kind fix
/kind refactor

#### What this PR does / why we need it:

Fixed #470 by removing `useConnectedPlayground()` which was deprecated, it auto-resolves the network on start by looking for a playground network to connect to. This implementation is just frustrating as it doesn't have a deterministic or static behavior to network resolution. DeFi Scan has removed this implementation recently as it was difficult to manage SSR and SPA network states, the resolution on DeFi Scan is now static too.
- This also fixes #473
- By removing `useConnectedPlayground()` playground local/remote resolution is now not automated anymore. By default, it will always resolve to the first network (which is "Local" for CI and development). During development, you must switch networks manually. And for e2e testing you must always use Local Network, you can start local network via `npm run playground:start`.
- To allow network switching easily during CI and testing, we can add it into "DeFi Playground", now "DeFi Testing".
- `PlaygroundScreen` has been refactored from "DeFi Playground" to "DeFi Testing" this refactor in large is to allow other networks to use the new "DeFi Testing" environment for features such as quick Wallet setup. A large part of the code into DeFi Playground has been refactored to be componentized. 

Fixed #471 by adding missing dependencies to `useMemo` in WalletAddressToken: `}, [wallet])`

Fixed #472 by deploying `whale:0.8.6`

Fixed #480 by adding a few missing dependencies to `useEffect`
- `}, [address])`
- `}, [wallet])`

Linked PRs: https://github.com/DeFiCh/wallet/pull/488 https://github.com/DeFiCh/wallet/pull/490

Fixed #423 #466

> I only tested these on `Web` and some parts of it on `Mobile`. @thedoublejay and someone else need to verify them

#### Additional comments?:

~~Many `useEffect` uses `}, [JSON.stringify(tokens)])` we should refactor this. `JSON.stringy()` shouldn't be a thing for `useEffect`. Many `useEffect` dependencies array is not well thought out, we need to be inspect them carefully.~~

Our context and provider are deeply nested which each resolution relying on a previous upstream provider/context this means if network changes whale will be updated, if whale is updated so must wallet, starting from: 
1. network
2. playground 
3. whale
4. wallet persistence 
5. defi scan
6. wallet store
7. wallet 
8. wallet address
9. transactions

```html
<ErrorBoundary>
  <NetworkProvider>
    <PlaygroundProvider>
      <WhaleProvider>
        <WalletPersistenceProvider>
          <DeFiScanProvider>
            <WalletStoreProvider>
              <SafeAreaProvider>
                <WalletNavigator />
                or
                <WalletProvider data={wallets[0]}>
                  <WalletAddressProvider>
                    <TransactionAuthorization />
                    <NavigationContainer>
                      <App.Navigator>
                        <App.Screen name='App' component={BottomTabNavigator} />
                        <App.Screen name='Playground' component={PlaygroundNavigator} />
                      </App.Navigator>
                    </NavigationContainer>
                  </WalletAddressProvider>
                </WalletProvider>
              </SafeAreaProvider>
            </WalletStoreProvider>
          </DeFiScanProvider>
        </WalletPersistenceProvider>
      </WhaleProvider>
    </PlaygroundProvider>
  </NetworkProvider>
</ErrorBoundary>
```

### CODE REVIEW

**Comment by thedoublejay** [comment]
@fuxingloh regarding the json.stringify dependency. I added it because it needs to be deep equality, like balance for example. It was actually recommended by one of the react mainteners. For ref https://stackoverflow.com/questions/59467758/passing-array-to-useeffect-dependency-list

**Comment by fuxingloh** [comment]
> @fuxingloh regarding the json.stringify dependency. I added it because it needs to be deep equality, like balance for example. It was actually recommended by one of the react mainteners. For ref https://stackoverflow.com/questions/59467758/passing-array-to-useeffect-dependency-list

Oh, didn't know this. Probably worth a refactor to unify our `useTokens()` implementation to be deeply reactive in the store. Probably wasn't a good idea to put dex state outside of store.

**Comment by thedoublejay** [comment]
@fuxingloh I'm adding some tests for this, I'll create a PR to your branch to test all these bugs.

**Comment by thedoublejay** [comment]
@fuxingloh  There's still an issue on the address side. 

Main problem:
1. Create a wallet in Local Network
2. Send some tokens, poolpairs etc.
2. Change network to Mainnet
3. Change back to Local
4. Tokens, poolpairs are not displayed.

The issue is on the initial wallet creation and the network switch, there are two different address created for the same Local Wallet. Since address is a parameter for all of our APIs, it doesn't return the correct value.

**Comment by fuxingloh** [comment]
> @fuxingloh
> Address is not the same on network change
> Main problem:
> 
> 1. Create a wallet in Local Network
> 2. Send some tokens, poolpairs etc.
> 3. Change network to Mainnet
> 4. Change back to Local
> 5. Tokens, poolpairs are not displayed.
> 
> The issue is on the initial wallet creation and the network switch, there are two different address created for the same Local Wallet. Since address is a parameter for all of our APIs, it doesn't return the correct value. Because of this, all user related data doesn't return correctly (e.g, PoolPairs, Balances etc.)
> 
> This PR - #488 has e2e tests that will pass if these bugs are fixed.

I will debug this now

**Comment by fuxingloh** [comment]
> > @fuxingloh
> > Address is not the same on network change
> > Main problem:
> > 
> > 1. Create a wallet in Local Network
> > 2. Send some tokens, poolpairs etc.
> > 3. Change network to Mainnet
> > 4. Change back to Local
> > 5. Tokens, poolpairs are not displayed.
> > 
> > The issue is on the initial wallet creation and the network switch, there are two different address created for the same Local Wallet. Since address is a parameter for all of our APIs, it doesn't return the correct value. Because of this, all user related data doesn't return correctly (e.g, PoolPairs, Balances etc.)
> > This PR - #488 has e2e tests that will pass if these bugs are fixed.
> 
> I will debug this now

The latest PR might fix it,

1. Added `address` to a 2 useEffect that might need it
2. `WalletStoreProvider` to only refresh on `wallets` deps since wallets depends on network
3. **Should be the root cause**: Added missing `dispatch` deps to `useTokenAPI` because store is now `useMemo()` and that causes store state to refresh, it's the last the refresh

**Comment by thedoublejay** [comment]
@fuxingloh I think the issue is the getWallet(0) address returns a different one. I saw it on the WalletAddressProvider, when setting on address it's a different address

**Review by thedoublejay — APPROVED** [review]
Nice fixes

**Comment by fuxingloh** [comment]
The dependencies array is just wild west now lol, we need to tackle them soon.

**Pull request merged**
