### PR TITLE
feature(ui-ux): add skeleton loader to balance screen

### LINKED ISSUE #970: Should use SkeletonLoader when loading `balances` instead of showing zeros.
#### What UI/UX improvements would you like to be implemented: 

Currently, we should 0 and empty tokens when loading balances, we should wait for balances and tokens to be loaded before we show any information.

#### Why is this needed:

To prevent scaring users that their funds are lost or missing. The UX is worst when their connectivity is bad.

> This might have been mentioned somewhere.

/triage accepted
/priority important-soon

### PR DESCRIPTION
**Pull request by kyleleow**
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
- To display skeleton loader in balance screen
- To not display `0` as balance amount when balance API has yet to return

#### Which issue(s) does this PR fixes?:

Fixes #970 

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x] No console errors on web
- [x] Tested on Light mode and Dark mode*
- [x] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [x] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

**Comment by pierregee** [comment]
1. Can we align the loaders?
 image
2. Curious if there's a way to handle these errors from the loader
image

**Comment by fullstackninja864** [comment]
Can we increase margin top here?
Screenshot 2022-02-15 at 3 56 58 PM

**Comment by chloezxyy** [comment]
Screenshot 2022-02-16 at 11 02 59 AM

Alignment issue on the DFI card, on the webapp, not sure if this will affect mobile view

**Comment by kyleleow** [comment]
I think we always have the priority of testing on mobile first then web, does it work on mobile?
For both the horizontal alignment issue from chloe and pierre should be from web, will address them

For @fullstackninja864 issue, can't seems to find that huge gap as shown in your screenshot on my ios, android and web, may I know what device did you test on?

**Comment by fullstackninja864** [comment]
@kyleleow I am testing on Samsung Galaxy A30S

**Review by pierregee — APPROVED** [review]

**Review by fullstackninja864 — APPROVED** [review]

**Review by pierregee — APPROVED** [review]

**Pull request merged**
