### PR TITLE
feature(ui-ux): add DFI price on balances page (#2286)

### LINKED ISSUE #2286: `balances` - add DFI price on balances page
#### What would you like to be added:
https://github.com/DeFiCh/wallet/discussions/2254

### PR DESCRIPTION
**Pull request by rox1338**
#### What kind of PR is this?:
/kind feature

#### What this PR does / why we need it:
Adding the DFI price to the DFIBalanceCard which is shown on the balances page.

#### Which issue(s) does this PR fixes?:
Fixes #2286

#### Developer Checklist:
- [ x] Read your code changes at least once
- [ ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x ] No console errors on web
- [ ] Tested on Light mode and Dark mode*
- [ ] Your UI implementation visually matched the rendered design*
- [ ] Unit tests*
- [ ] Added e2e tests*
- [ ] Added translations*

### CODE REVIEW

**Comment by rox1338** [comment]
image

**Comment by thedoublejay** [comment]
Hi @rox1338! Thanks for the PR. We're using designs from our design team for our improvements. I'll send your changes if it's ok with them.

**Comment by thedoublejay** [comment]
Hi @rox1338, checking with the design team. I think we will not proceed with this ticket at all. One thing to check before working on an open issue is, if it has a `triage/accepted` label. Currently this issue is still under triage and we haven't discussed it yet. Thanks!

**Comment by rox1338** [comment]
> Hi @rox1338, checking with the design team. I think we will not proceed with this ticket at all. One thing to check before working on an open issue is, if it has a `triage/accepted` label. Currently this issue is still under triage and we haven't discussed it yet. Thanks! Feel free to close the PR

Okay, thank you for the info.

**Pull request closed without merging**
